apiVersion: v1
kind: Namespace
metadata:
    name: demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
    name: blue-green-rollout-demo
    namespace: demo
spec:
    replicas: 2 
    revisionHistoryLimit: 2
    selector:
        matchLabels:
            app: blue-green-rollout-demo
    template:
        metadata:
            labels:
                app: blue-green-rollout-demo
        spec:
            containers:
            - name: blue-green-rollout-demo
              image: argoproj/rollouts-demo:blue
              ports:
              - containerPort: 8080
    strategy:
        blueGreen:
            activeService: blue-green-rollout-demo-active
            previewService: blue-green-rollout-demo-preview
            # previewReplicaCount: 1
            autoPromotionEnabled: false
            # autoPromotionSeconds: 30
            # scaleDownDelaySeconds: 43200
            
---
kind: Service
apiVersion: v1
metadata:
    name: blue-green-rollout-demo-active
    namespace: demo
spec:
    type: NodePort
    selector:
        app: blue-green-rollout-demo
    ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
    name: blue-green-rollout-demo-preview
    namespace: demo
spec:
    type: NodePort
    selector:
        app: blue-green-rollout-demo
    ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
      protocol: TCP