apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: ingressgateway
    namespace: argocd
spec:
    project: istio
    source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: gateway
        targetRevision: 1.19.0
    destination:
        server: https://kubernetes.default.svc
        namespace: istio-ingress
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
        - CreateNamespace=true