apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: istio
    namespace: argocd
spec:
    project: istio
    sources:
        - repoURL: https://istio-release.storage.googleapis.com/charts
          chart: base
          targetRevision: 1.19.0
        - repoURL: https://istio-release.storage.googleapis.com/charts
          chart: istiod
          targetRevision: 1.19.0
    destination:
        server: https://kubernetes.default.svc
        namespace: istio-system
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
        - CreateNamespace=true