kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  namespace: demo
  name: canary-demo-dr
spec:
  host: canary-demo-service.demo.svc.cluster.local
  subsets:
    - name: v1
      labels:
        app: canary-demo
    - name: v2
      labels:
        app: canary-demo
---
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  namespace: demo
  name: canary-demo-vs
spec:
  http:
    - name: primary
      route:
        - destination:
            host: canary-demo-service.demo.svc.cluster.local
            subset: v1
          weight: 100
        - destination:
            host: canary-demo-service.demo.svc.cluster.local
            subset: v2
          weight: 0
    # rollout이 step에 따라 라우팅 규칙을 자동으로 추가한다.
  hosts:
    - canary-demo-service.demo.svc.cluster.local
  gateways:
    - demo/demo-gw
