projects:
  - name: istio
    namespace: argocd
    description: istio project
    sourceRepos:
      - '*'
    destinations:
      - namespace: '*'
        server: '*'
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
applications:
  - name: istio-app-of-app
    namespace: argocd
    project: istio
    additionalAnnotations:
        "helm.sh/resource-policy": keep
    source:
      repoURL: https://github.com/SDB016/argo-demo.git
      targetRevision: HEAD
      path: istio/applications
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

