# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#     name: blue-green-deployment
#     namespace: argocd
# spec:
#     project: istio
#     source:
#         repoURL: https://github.com/SDB016/argo-demo.git
#         chart: blue-green-deployment
#         targetRevision: 0.1.0
#         helm:
#             values: |
#               v1weight: 100
#     destination:
#         server: https://kubernetes.default.svc
#         namespace: bookinfo