# Istio base
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: istio-base
    namespace: argo
spec:
    project: istio
    source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: base
        targetRevision: 1.19.0
    destination:
        server: https://kubernetes.default.svc
        namespace: istio-system
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
        - CreateNamespace=true
---
# Istiod
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: istiod
    namespace: argo
spec:
    project: istio
    source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: istiod
        targetRevision: 1.19.0
    destination:
        server: https://kubernetes.default.svc
        namespace: istio-system
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
        - CreateNamespace=true